### ISSUE TITLE
Error making extern call w/ native state field

### ISSUE THREAD

**Issue by seizethedave** [uwplse/cozy#11]
e.g.

```
TokenGroupNativeBug:
    type OffsetAttribute = Native "OffsetAttribute"
    extern startOffset(att : OffsetAttribute) : Int = "{att}.startOffset()"
    state offset : OffsetAttribute

    query getStart()
        startOffset(offset)
```
produces this error:

```
D-173-250-185-41:cozy dgrant$ cozy --simple  --java out.java specs/TokenGroupNativeBug.ds
Checking assumptions...
Done!

_var12 : OffsetAttribute = offset

TokenGroupNativeBug:
  type OffsetAttribute = OffsetAttribute
  state _var12 : OffsetAttribute
  query getStart():
    startOffset(_var12)

Generating final concrete implementation...
# impls: 1
_var12 ~~> OffsetAttribute

[('_var12', TNative('OffsetAttribute'))]
Code generation failed!
Implementation was dumped to /tmp/failed_codegen.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/cozy", line 11, in <module>
    load_entry_point('Cozy', 'console_scripts', 'cozy')()
  File "/Users/dgrant/Dev/cozy/cozy/cozy/main.py", line 139, in run
    out.write(codegen.JavaPrinter(boxed=(not args.unboxed)).visit(impl, state_map, share_info))
  File "/Users/dgrant/Dev/cozy/cozy/cozy/common.py", line 149, in visit
    return getattr(self, visit_func)(x, *args, **kwargs)
  File "/Users/dgrant/Dev/cozy/cozy/cozy/codegen/java.py", line 48, in visit_Spec
    s += self.visit(setup, INDENT + INDENT)
  File "/Users/dgrant/Dev/cozy/cozy/cozy/common.py", line 149, in visit
    return getattr(self, visit_func)(x, *args, **kwargs)
  File "/Users/dgrant/Dev/cozy/cozy/cozy/codegen/cxx.py", line 592, in visit_SEscape
    setups, args = zip(*[self.visit(arg, indent) for arg in args])
  File "/Users/dgrant/Dev/cozy/cozy/cozy/codegen/cxx.py", line 592, in <listcomp>
    setups, args = zip(*[self.visit(arg, indent) for arg in args])
  File "/Users/dgrant/Dev/cozy/cozy/cozy/common.py", line 149, in visit
    return getattr(self, visit_func)(x, *args, **kwargs)
  File "/Users/dgrant/Dev/cozy/cozy/cozy/codegen/cxx.py", line 585, in visit_Exp
    raise NotImplementedError(e)
NotImplementedError: ENative(ENum(0).with_type(TInt())).with_type(TNative('OffsetAttribute'))
```

Whereas if startOffset is called with a _parameter_ of type OffsetAttribute, it works fine.

**Comment by Calvin-L** [comment]
There are several places where Cozy expects to be able to produce a "default value" of a given type. That works fine for ints (default value zero) and collections (default value empty), but native types are trickier. (Well, they are easier in C++ where every sensible type has a zero-argument constructor.) Internally Cozy has a thing called `ENative(...)` which you see in the stacktrace that represents "something of this type", but it isn't sure how to actually make one concretely.

The right fix is for the Java codegen pass to implement `visit_ENative` to default-construct native types in the manner you expect:
 - unboxed native types like `float` get special values like `0.0f`
 - boxed native types get `null`

The relevant line:
https://github.com/uwplse/cozy/blob/63924678462bee79558a2f4cf72bb446eb8d24f0/cozy/codegen/java.py#L47
