### ISSUE TITLE
min, max operators not yet implemented

### ISSUE THREAD

**Issue by seizethedave** [uwplse/cozy#6]
Syntax support is there, but:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/cozy", line 11, in <module>
    load_entry_point('Cozy', 'console_scripts', 'cozy')()
  File "/Users/dgrant/Dev/cozy/cozy/cozy/main.py", line 49, in run
    errors = typecheck.typecheck(ast)
  File "/Users/dgrant/Dev/cozy/cozy/cozy/typecheck.py", line 13, in typecheck
    typechecker.visit(ast)
  File "/Users/dgrant/Dev/cozy/cozy/cozy/typecheck.py", line 590, in visit
    res = super().visit(x)
  File "/Users/dgrant/Dev/cozy/cozy/cozy/common.py", line 141, in visit
    return getattr(self, visit_func)(x, *args, **kwargs)
  File "/Users/dgrant/Dev/cozy/cozy/cozy/typecheck.py", line 84, in visit_Spec
    self.visit(op)
  File "/Users/dgrant/Dev/cozy/cozy/cozy/typecheck.py", line 590, in visit
    res = super().visit(x)
  File "/Users/dgrant/Dev/cozy/cozy/cozy/common.py", line 141, in visit
    return getattr(self, visit_func)(x, *args, **kwargs)
  File "/Users/dgrant/Dev/cozy/cozy/cozy/typecheck.py", line 528, in visit_Query
    self.visit(q.ret)
  File "/Users/dgrant/Dev/cozy/cozy/cozy/typecheck.py", line 590, in visit
    res = super().visit(x)
  File "/Users/dgrant/Dev/cozy/cozy/cozy/common.py", line 141, in visit
    return getattr(self, visit_func)(x, *args, **kwargs)
  File "/Users/dgrant/Dev/cozy/cozy/cozy/typecheck.py", line 243, in visit_EUnaryOp
    raise NotImplementedError(e.op)
NotImplementedError: max
```

**Comment by Calvin-L** [comment]
Min and max are now supported for bags of ints (b71ca206b3463c3a40bba8733ac2570f7451aac1).

The synthesizer doesn't do a great job with specifications involving these primitives, but they at least work.
